version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - yes | apt-get install g++-multilib
      - yes | apt-get install libpcsclite-dev
      - yes | apt-get install libpcsclite1
      #- npm install pcsclite
      - yes | apt-get install pcscd
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
    - npm run build:package
    - npm run build:msi_x86
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./**/*
